"""Curated angling tips data for tips.csv.

Each entry is a dict with keys matching the tips schema (minus auto id).
Sources cited where confidence >= 3 per plan-3 §Data Quality.

Coverage target: >=18 tips per species across 15 species.
Mix of season, baro_trend, moon_phase, time_of_day for breadth.
Region 11 = Quebec (QC).
"""

from __future__ import annotations


# Common source URLs (kept short, referenced by name in the data)
S = {
    "sepaq": "https://www.sepaq.com/peche/index.dot",
    "qpeche": "https://www.quebecpeche.com/",
    "dfo": "https://www.dfo-mpo.gc.ca/species-especes/profiles-profils-eng.html",
    "infisherman": "https://www.in-fisherman.com/editorial/",
    "bassmaster": "https://www.bassmaster.com/tips/",
    "fns": "https://www.fieldandstream.com/fishing/",
    "infopeche": "https://infopeche.com/",
    "book_lindner": "book://lindner/multi-species-angler/ch3",
    "book_critical_walleye": "book://in-fisherman/critical-concepts/walleye",
    "book_critical_bass": "book://in-fisherman/critical-concepts/largemouth-bass",
    "book_critical_pike": "book://in-fisherman/critical-concepts/pike-muskie",
    "book_critical_trout": "book://in-fisherman/critical-concepts/trout",
}


# Helper to build a row dict
def t(
    species_id: int,
    fr: str,
    en: str,
    *,
    region_id: int | str = "",
    water_type_id: int | str = "",
    season: str = "any",
    baro_trend: str = "any",
    moon_phase: str = "any",
    temp_water_min_c: float | str = "",
    temp_water_max_c: float | str = "",
    time_of_day: str = "any",
    source_url: str = "",
    confidence: int = 3,
) -> dict[str, str]:
    return {
        "species_id": str(species_id),
        "region_id": str(region_id),
        "water_type_id": str(water_type_id),
        "season": season,
        "baro_trend": baro_trend,
        "moon_phase": moon_phase,
        "temp_water_min_c": str(temp_water_min_c),
        "temp_water_max_c": str(temp_water_max_c),
        "time_of_day": time_of_day,
        "tip_text_fr": fr,
        "tip_text_en": en,
        "source_url": source_url,
        "confidence": str(confidence),
    }


TIPS: list[dict[str, str]] = [
    # ============================================================
    # 1 — Achigan à grande bouche / Largemouth Bass (≥18 tips)
    # ============================================================
    t(
        1,
        "Au printemps, cibler les baies peu profondes au sud du lac qui réchauffent en premier; les bass migrent vers ces zones pour la reproduction.",
        "In spring, target shallow southern bays that warm first; bass migrate there to spawn.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=12,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Période de fraie: ralentir les présentations sur les nids visibles, ver souple no-weight type Senko en pitching court.",
        "Spawn window: slow presentations on visible beds with a weightless stick-worm pitched short.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=15,
        temp_water_max_c=20,
        source_url=S["book_critical_bass"],
        confidence=5,
    ),
    t(
        1,
        "Après-fraie: les femelles épuisées restent près des herbiers; jig finesse ou tube en glissement lent.",
        "Post-spawn: spent females linger near weed edges; finesse jig or tube glided slowly.",
        season="spring",
        baro_trend="steady",
        water_type_id=1,
        temp_water_min_c=18,
        temp_water_max_c=22,
        time_of_day="morning",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Été chaud (>25°C surface): pêcher en début de matinée et tard en soirée, topwater walking sur platières herbeuses.",
        "Hot summer (>25°C surface): fish early and late, walking topwater over weedy flats.",
        season="summer",
        water_type_id=1,
        temp_water_min_c=22,
        temp_water_max_c=28,
        time_of_day="dawn",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Mi-journée d'été: les bass descendent sur le bord des herbiers profonds; Texas rig avec ver souple en glissement.",
        "Summer midday: bass drop to deep weed edges; Texas-rig worm dragged slowly.",
        season="summer",
        water_type_id=1,
        time_of_day="midday",
        temp_water_max_c=28,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Pression barométrique en chute avant un orage: fenêtre dorée pour le topwater et les spinnerbaits rapides.",
        "Falling pressure before a storm: golden window for topwater and fast-moving spinnerbaits.",
        season="summer",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        1,
        "Après le passage d'un front froid: rétrograder vers le drop-shot ou shaky head, ralentir au maximum.",
        "After a cold-front passage: downshift to drop-shot or shaky head, slow it way down.",
        baro_trend="rising",
        source_url=S["book_critical_bass"],
        confidence=5,
    ),
    t(
        1,
        "Automne: les bass suivent les bancs de gardons; crankbait à bavette moyenne en imitation de proie.",
        "Fall: bass follow shad schools; medium-bill crankbait in baitfish patterns.",
        season="fall",
        water_type_id=1,
        temp_water_min_c=12,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Fin d'automne en eau qui refroidit: jerkbait suspendu avec pauses longues de 4-8 secondes.",
        "Late fall as water cools: suspending jerkbait with long 4-8 sec pauses.",
        season="fall",
        temp_water_min_c=8,
        temp_water_max_c=14,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        1,
        "Eau muddy après pluie: leurres avec vibration et profil contrasté (chartreuse/noir), spinnerbait pale Colorado.",
        "Muddy water after rain: vibrating lures with high-contrast profile (chartreuse/black), Colorado-blade spinnerbait.",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Pleine lune chaude: activité nocturne accrue sur les pointes, jig noir trainé lentement.",
        "Warm full moon: increased night activity on points; black jig dragged slowly.",
        moon_phase="full",
        time_of_day="night",
        season="summer",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        1,
        "Eau teintée (visibilité 30-60 cm): leurres en chartreuse ou orange, vibration > silhouette.",
        "Stained water (30-60 cm visibility): chartreuse or orange lures, vibration over silhouette.",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Bordures de nénuphars: pitching d'un creature-bait en Texas rig avec poids 3/8 oz pour pénétrer.",
        "Lily pad edges: pitch a creature-bait Texas-rigged with a 3/8 oz weight to punch through.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Quais et débarcadères: pitching skip avec ver souple sous l'ombre, 2-4 pieds de profondeur.",
        "Docks: skip a soft stick worm into the shadow line, 2-4 ft deep.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Au Québec, les bass de plus de 4 lb se prennent souvent sur des points rocheux avec herbiers adjacents.",
        "In Quebec, bass over 4 lb often come off rocky points with adjacent weeds.",
        region_id=11,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        1,
        "Eau froide de printemps (<12°C): suspending jerkbait à 5-10 pieds, pauses très longues.",
        "Early-spring cold water (<12°C): suspending jerkbait at 5-10 ft, very long pauses.",
        season="spring",
        temp_water_min_c=8,
        temp_water_max_c=12,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        1,
        "Tournoi: alterner deux patterns différents (power-fishing matin, finesse midi) pour maximiser le poids.",
        "Tournament: alternate two patterns (power-fishing AM, finesse midday) to maximize weight.",
        source_url=S["bassmaster"],
        confidence=3,
    ),
    t(
        1,
        "Bouillonnements de surface: lancer immédiatement un walking topwater ou un buzzbait derrière la commotion.",
        "Surface boils: cast a walking topwater or buzzbait right behind the commotion immediately.",
        season="summer",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Lune décroissante en eau claire: présentations finesse drop-shot ou Neko en couleurs naturelles.",
        "Waning moon in clear water: finesse drop-shot or Neko-rig in natural colors.",
        moon_phase="waning",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        1,
        "Petits étangs urbains: lancer parallèle à la berge avec un swim jig en glissement constant.",
        "Small urban ponds: cast parallel to the bank with a steady swim-jig retrieve.",
        water_type_id=3,
        source_url=S["fns"],
        confidence=3,
    ),
    # ============================================================
    # 2 — Achigan à petite bouche / Smallmouth Bass (≥18 tips)
    # ============================================================
    t(
        2,
        "Smallmouth aime les fonds rocheux et le courant; les pointes rocheuses sont des aimants à smallies.",
        "Smallmouth love rocky bottoms and current; rocky points are smallie magnets.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Printemps en eau qui se réchauffe (10-15°C): tube sur fond, dragué lentement sur sable et roches.",
        "Spring as water warms (10-15°C): tube bait dragged slowly along sand and rock.",
        season="spring",
        temp_water_min_c=10,
        temp_water_max_c=15,
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        2,
        "Période de fraie: nids visibles sur fond de sable ou gravier; ne pas insister pour la conservation de l'espèce.",
        "Spawn: visible beds on sand or gravel; do not pressure for conservation reasons.",
        season="spring",
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        2,
        "Été: drop-shot avec petit ver flick-shake à 10-25 pieds sur talus rocheux.",
        "Summer: drop-shot with small flick-shake worm at 10-25 ft on rocky breaks.",
        season="summer",
        temp_water_min_c=18,
        temp_water_max_c=24,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Smallie chasseur en surface: walking topwater couleur naturelle (gris/blanc) au lever du jour.",
        "Surface-feeding smallie: walking topwater in natural colors (gray/white) at dawn.",
        time_of_day="dawn",
        season="summer",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Rivières à courant modéré: jig finesse 1/8 oz dérivé dans les replats derrière les roches.",
        "Moderate-current rivers: 1/8 oz finesse jig drifted in slack water behind boulders.",
        water_type_id=2,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Front froid: les smallies se collent au fond et refusent les présentations rapides; ned rig en glissement.",
        "Cold front: smallies hug bottom and refuse fast moves; Ned rig dragged slowly.",
        baro_trend="rising",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Pré-frontale: jerkbait suspendu en couleur ayu ou perchaude, twitch-twitch-pause de 3 sec.",
        "Pre-front: suspending jerkbait in ayu or perch color, twitch-twitch-3sec-pause.",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Automne: smallies se concentrent sur les pointes vers le lac principal; crankbait deep en imitation de proie.",
        "Fall: smallies gang up on main-lake points; deep crankbait in baitfish patterns.",
        season="fall",
        temp_water_min_c=10,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Eau claire (>3 m de visibilité): fluorocarbone fin (6-8 lb) et présentations naturelles.",
        "Clear water (>3 m visibility): light fluorocarbon (6-8 lb) and natural presentations.",
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        2,
        "Au Québec, le fleuve Saint-Laurent abrite des smallies trophées (>4 lb) près des îles rocheuses.",
        "In Quebec, the St. Lawrence holds trophy smallies (>4 lb) near rocky islands.",
        region_id=11,
        water_type_id=4,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        2,
        "Sépaq: dans les réserves fauniques, viser tôt le matin et fin d'après-midi en juin-juillet.",
        "Sepaq: in wildlife reserves, target early morning and late afternoon in June-July.",
        region_id=11,
        season="summer",
        source_url=S["sepaq"],
        confidence=4,
    ),
    t(
        2,
        "Smallmouth en hiver (eau <8°C): jig hair en couleurs naturelles, présentation extrêmement lente sur fond.",
        "Winter smallmouth (<8°C): hair jig in natural colors, extremely slow bottom presentation.",
        season="winter",
        temp_water_max_c=8,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Pleine lune d'été: activité crépusculaire prolongée jusqu'à 22h sur les pointes.",
        "Summer full moon: extended dusk activity until 10 PM on points.",
        moon_phase="full",
        time_of_day="dusk",
        season="summer",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        2,
        "Goujon (gobie) abondant: imiter avec un tube brun-vert ou ned rig couleur cigare.",
        "Where round gobies are abundant: imitate with a brown-green tube or cigar-colored Ned rig.",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Rivière des Outaouais et fleuve: drop-shot lourd 1/2 oz pour tenir dans le courant 20-30 pieds.",
        "Ottawa River / St. Lawrence: heavy 1/2 oz drop-shot to hold in 20-30 ft current.",
        water_type_id=4,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        2,
        "Smallie agressif: spinnerbait double-willow chartreuse-blanc retiré rapidement près des roches.",
        "Aggressive smallie: chartreuse-white double-willow spinnerbait reeled fast near rocks.",
        source_url=S["bassmaster"],
        confidence=3,
    ),
    t(
        2,
        "Eau muddy après tempête: les smallies se déplacent vers les pointes peu profondes; vibration > visuel.",
        "Muddy water after storm: smallies move to shallow points; vibration over visual.",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        2,
        "Lune nouvelle: période minor matinale très productive sur les talus de 15-20 pieds.",
        "New moon: morning minor period very productive on 15-20 ft breaks.",
        moon_phase="new",
        time_of_day="morning",
        source_url=S["infisherman"],
        confidence=3,
    ),
    # ============================================================
    # 3 — Doré jaune / Walleye (≥18 tips)
    # ============================================================
    t(
        3,
        "Doré préfère la basse lumière: aube, crépuscule et nuit nuageuse, surtout dans l'eau claire.",
        "Walleye prefer low light: dawn, dusk and overcast nights, especially in clear water.",
        time_of_day="dawn",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Printemps post-fraie: jig 1/4 oz avec ver de terre dérivé sur fonds graveleux 6-12 pieds.",
        "Post-spawn spring: 1/4 oz jig with worm drifted on 6-12 ft gravel.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=10,
        temp_water_max_c=15,
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Été sur grand lac: troller un crawler harness 1.0-1.5 mph sur les structures profondes 20-35 pieds.",
        "Summer on big water: troll crawler harness 1.0-1.5 mph on deep 20-35 ft structures.",
        season="summer",
        water_type_id=1,
        temp_water_min_c=18,
        temp_water_max_c=24,
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        3,
        "Doré préfère les températures 13-21°C; au-dessus de 24°C, il descend en profondeur sous la thermocline.",
        "Walleye prefer 13-21°C; above 24°C they drop below the thermocline.",
        source_url=S["dfo"],
        confidence=5,
    ),
    t(
        3,
        "Crépuscule: remontée des dorés sur les pointes; jig 3/8 oz avec ver ou vairon.",
        "Dusk: walleye move up onto points; 3/8 oz jig with worm or minnow.",
        time_of_day="dusk",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Doré en eau teintée (Saint-Laurent, rivières du Bouclier): meilleur que le doré en eau claire pour les heures de midi.",
        "Stained water walleye (St. Lawrence, Shield rivers): more active midday than clear-water walleye.",
        time_of_day="midday",
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Tendance baro chute: les dorés montent et chassent activement; crankbait shallow en couleur tigre.",
        "Falling barometer: walleye come up and feed actively; shallow tiger-pattern crankbait.",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Post-front (baro hausse): retour aux jigs lents sur fond, vairon mort sur jig 1/8 oz.",
        "Post-front (rising baro): back to slow jigs on bottom, dead minnow on 1/8 oz jig.",
        baro_trend="rising",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Pleine lune d'été: pêche nocturne très efficace sur les hauts-fonds 6-10 pieds.",
        "Summer full moon: night fishing very effective on 6-10 ft shallow flats.",
        moon_phase="full",
        time_of_day="night",
        season="summer",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Lac Saint-Jean (QC): doré et ouananiche cohabitent; troller à 8-12 pieds avec spoon argent-bleu.",
        "Lac Saint-Jean (QC): walleye and landlocked salmon coexist; troll 8-12 ft with silver-blue spoon.",
        region_id=11,
        water_type_id=1,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        3,
        "Automne: les dorés se gavent avant l'hiver; jerkbait suspendu en eau de 10-20 pieds, pauses 5-8 sec.",
        "Fall: walleye feed up before winter; suspending jerkbait in 10-20 ft, 5-8 sec pauses.",
        season="fall",
        temp_water_min_c=8,
        temp_water_max_c=14,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Hiver (pêche blanche): vairon vif sur dandinette dorée 1/4 oz, à 1-2 pieds du fond.",
        "Winter (ice fishing): live minnow on gold jigging spoon 1/4 oz, 1-2 ft off bottom.",
        season="winter",
        temp_water_max_c=4,
        region_id=11,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Vent qui souffle vers une berge: les dorés se concentrent côté vagues, où le plancton s'accumule.",
        "Wind blowing into a shoreline: walleye stack on the wave-washed side where plankton concentrates.",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Période minor solunar coïncidant avec crépuscule: probabilité élevée d'un pic d'activité.",
        "Solunar minor period overlapping dusk: high probability of an activity spike.",
        time_of_day="dusk",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        3,
        "Doré refuse une présentation: changer la couleur (jaune-vif, orange) avant la taille du leurre.",
        "Walleye refuses a presentation: switch color (bright yellow, orange) before switching lure size.",
        source_url=S["book_critical_walleye"],
        confidence=4,
    ),
    t(
        3,
        "Embouchure de rivière au printemps: dorés en remontée, jig 1/4 oz avec twister sur talus.",
        "River mouth in spring: ascending walleye, 1/4 oz jig with twister tail on breakline.",
        season="spring",
        water_type_id=2,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Lune nouvelle: période major nocturne, troller lentement (1.0 mph) avec crankbait shad.",
        "New moon: major night period, troll slowly (1.0 mph) with shad crankbait.",
        moon_phase="new",
        time_of_day="night",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        3,
        "Doré de trophée (>8 lb): souvent solitaire, sur structure isolée; live bait rig avec vairon de 15 cm.",
        'Trophy walleye (>8 lb): often solitary on isolated structure; live-bait rig with 6" sucker.',
        source_url=S["book_critical_walleye"],
        confidence=4,
    ),
    t(
        3,
        "Doré jaune sépaq Lac-Bouchard: pêche guidée mai-juin, jig vert-orange préféré.",
        "Sepaq Lac-Bouchard walleye: guided May-June fishing, green-orange jig preferred.",
        region_id=11,
        water_type_id=1,
        season="spring",
        source_url=S["sepaq"],
        confidence=3,
    ),
    # ============================================================
    # 4 — Doré noir / Sauger (≥18 tips)
    # ============================================================
    t(4, "Le doré noir préfère les eaux turbides à très turbides, contrairement au doré jaune.",
      "Sauger prefers turbid to very turbid waters, unlike walleye.",
      source_url=S["dfo"], confidence=5),
    t(4, "Cours d'eau à fort débit: doré noir tient dans les replats derrière les structures.",
      "Strong-current rivers: sauger holds in slack water behind structure.",
      water_type_id=2, source_url=S["infisherman"], confidence=4),
    t(4, "Été: troller un crawler harness à 1.2-1.5 mph sur fonds sablonneux 15-25 pieds.",
      "Summer: troll a crawler harness at 1.2-1.5 mph over 15-25 ft sand flats.",
      season="summer", water_type_id=4, source_url=S["infisherman"], confidence=4),
    t(4, "Aube et crépuscule: jig 3/8 oz avec vairon vif sur le bord des fosses profondes.",
      "Dawn and dusk: 3/8 oz jig with live minnow on the edge of deep holes.",
      time_of_day="dawn", source_url=S["book_critical_walleye"], confidence=4),
    t(4, "Front qui approche: les saugers montent et chassent, crankbait shad-imitateur dans les hauts-fonds.",
      "Approaching front: sauger moves up and feeds; shad-pattern crankbait on shallow flats.",
      baro_trend="falling", source_url=S["infisherman"], confidence=4),
    t(4, "Post-front: ralentir présentations, jig 1/4 oz avec twister sur 25-35 pieds.",
      "Post-front: slow presentations, 1/4 oz jig with twister on 25-35 ft.",
      baro_trend="rising", source_url=S["book_critical_walleye"], confidence=4),
    t(4, "Saugers en bancs serrés: lorsqu'on en prend un, lancer immédiatement au même endroit.",
      "Sauger in tight schools: once you catch one, cast right back to the same spot.",
      source_url=S["infisherman"], confidence=5),
    t(4, "Couleurs gagnantes en eau turbide: orange-jaune fluo, chartreuse-firetiger.",
      "Winning colors in turbid water: hot orange-yellow, chartreuse-firetiger.",
      source_url=S["bassmaster"], confidence=4),
    t(4, "Pêche d'hiver sur glace: dandinette jaune-or 1/4 oz avec tête de vairon, 1-3 m sous la glace.",
      "Ice fishing: yellow-gold 1/4 oz jigging spoon with minnow head, 1-3 m under ice.",
      season="winter", region_id=11, source_url=S["qpeche"], confidence=4),
    t(4, "Printemps: saugers se concentrent au pied des barrages où les frayères sont accessibles.",
      "Spring: sauger concentrates at the foot of dams where spawning gravel is accessible.",
      season="spring", water_type_id=4, source_url=S["infisherman"], confidence=4),
    t(4, "Doré noir trophée: souvent dans 30-50 pieds en été, jigging spoon argent ou doré sur le fond.",
      "Trophy sauger: often in 30-50 ft in summer; silver or gold jigging spoon on bottom.",
      season="summer", source_url=S["book_critical_walleye"], confidence=3),
    t(4, "Saint-Laurent (QC): saugers tiennent près des piles de pont et structures artificielles.",
      "St. Lawrence (QC): sauger holds near bridge pilings and man-made structures.",
      region_id=11, water_type_id=4, source_url=S["qpeche"], confidence=3),
    t(4, "Pleine lune: période major nocturne pour doré noir en lac, troller à 1.0 mph.",
      "Full moon: major night period for sauger in lakes, troll at 1.0 mph.",
      moon_phase="full", time_of_day="night", source_url=S["infisherman"], confidence=3),
    t(4, "Eau qui se réchauffe au printemps: 10-13°C est la fenêtre clé pour activité maximale.",
      "Spring warm-up: 10-13°C is the key window for max activity.",
      season="spring", temp_water_min_c=10, temp_water_max_c=13,
      source_url=S["dfo"], confidence=4),
    t(4, "Vent fort qui rapproche les vagues d'une berge: saugers chassent sur le côté battu.",
      "Strong wind pushing waves into shore: sauger feeds on the wave-washed side.",
      source_url=S["book_critical_walleye"], confidence=4),
    t(4, "Lune nouvelle: minor matinal souvent meilleur que major en eau turbide.",
      "New moon: morning minor often better than major in turbid water.",
      moon_phase="new", time_of_day="morning", source_url=S["infisherman"], confidence=3),
    t(4, "Automne: saugers se gavent avant le froid; crankbait à bavette deep 15-25 pieds.",
      "Fall: sauger feeds heavily before cold; deep-bill crankbait 15-25 ft.",
      season="fall", temp_water_min_c=8, temp_water_max_c=15,
      source_url=S["infisherman"], confidence=4),
    t(4, "Doré noir refuse une présentation: descendre en taille (1/8 oz) avant tout autre changement.",
      "Sauger refuses a presentation: downsize (1/8 oz) before any other change.",
      source_url=S["book_critical_walleye"], confidence=3),
    t(4, "Pêche en train avec downrigger: doré noir d'été à 22-30 pieds sur thermocline.",
      "Downrigger trolling: summer sauger at 22-30 ft on the thermocline.",
      season="summer", source_url=S["infisherman"], confidence=3),

    # ============================================================
    # 5 — Grand brochet / Northern Pike (≥18 tips)
    # ============================================================
    t(5, "Brochet préfère les eaux 10-20°C et les herbiers; au-dessus de 22°C il devient léthargique.",
      "Pike prefer 10-20°C and weed beds; above 22°C they become lethargic.",
      source_url=S["dfo"], confidence=5),
    t(5, "Printemps post-fraie (eau 6-12°C): brochets affamés dans les baies peu profondes.",
      "Post-spawn spring (6-12°C): ravenous pike in shallow bays.",
      season="spring", water_type_id=1, temp_water_min_c=6, temp_water_max_c=12,
      source_url=S["book_critical_pike"], confidence=5),
    t(5, "Spinnerbait 1 oz double-willow en argent-bleu: arme classique pour brochet sur herbiers.",
      "1 oz double-willow silver-blue spinnerbait: classic weed-bed pike weapon.",
      source_url=S["book_critical_pike"], confidence=5),
    t(5, "Été chaud: viser herbiers profonds 15-25 pieds, troller un swimbait paddle-tail 6\".",
      "Hot summer: target 15-25 ft deep weeds, troll a 6\" paddle-tail swimbait.",
      season="summer", temp_water_min_c=22, source_url=S["infisherman"], confidence=4),
    t(5, "Pré-frontale (baro chute): fenêtre brûlante, gros leurres et vitesse, walking topwater.",
      "Pre-front (falling baro): blazing hot window, big lures and speed, walking topwater.",
      baro_trend="falling", source_url=S["book_critical_pike"], confidence=5),
    t(5, "Post-front: brochet apathique, jerkbait suspendu avec pauses longues 6-10 sec.",
      "Post-front: lethargic pike, suspending jerkbait with long 6-10 sec pauses.",
      baro_trend="rising", source_url=S["infisherman"], confidence=4),
    t(5, "Automne (eau qui refroidit): les gros brochets remontent vers les hauts-fonds chasser.",
      "Fall (cooling water): big pike move shallow to feed.",
      season="fall", temp_water_min_c=8, temp_water_max_c=14,
      source_url=S["book_critical_pike"], confidence=5),
    t(5, "Bouchée de brochet: ferrer FORT 2 fois, ces poissons ont la gueule très dure.",
      "Pike bite: hammer the hookset twice, their mouths are bony.",
      source_url=S["bassmaster"], confidence=4),
    t(5, "Cuillère ondulante Daredevle rouge-blanc: le leurre classique brochet depuis 100 ans.",
      "Red-white Daredevle spoon: the classic 100-year pike lure.",
      source_url=S["book_critical_pike"], confidence=4),
    t(5, "Bas de ligne en acier ou fluorocarbone 80 lb obligatoire: les dents tranchent tout reste.",
      "Steel or 80 lb fluorocarbon leader mandatory: the teeth cut everything else.",
      source_url=S["fns"], confidence=5),
    t(5, "Pêche d'hiver sur glace: balance-tipup avec gros vairon de 10-15 cm sur les talus.",
      "Ice fishing: tip-up with big 10-15 cm shiner on breaklines.",
      season="winter", region_id=11, source_url=S["qpeche"], confidence=4),
    t(5, "Brochet trophée (>40\"): souvent solitaire, gros leurre 10-12\" troller lentement.",
      "Trophy pike (>40\"): often solitary; big 10-12\" lure trolled slowly.",
      source_url=S["book_critical_pike"], confidence=4),
    t(5, "Au Québec, les baies de la rivière des Outaouais produisent des brochets nombreux mai-juin.",
      "In Quebec, Ottawa River bays produce numerous pike in May-June.",
      region_id=11, season="spring", source_url=S["qpeche"], confidence=3),
    t(5, "Crapet ou petit doré comme appât vif: présenter au-dessus des herbiers profonds.",
      "Pumpkinseed or small walleye as live bait: present over deep weed flats.",
      source_url=S["infisherman"], confidence=3),
    t(5, "Pleine lune d'été: activité prolongée au crépuscule, jerkbait grand format sur platières.",
      "Summer full moon: extended dusk activity, big jerkbait on flats.",
      moon_phase="full", time_of_day="dusk", season="summer",
      source_url=S["infisherman"], confidence=3),
    t(5, "Brochet en eau muddy: spinnerbait colorado-blade chartreuse, vibration > silhouette.",
      "Muddy-water pike: chartreuse Colorado-blade spinnerbait, vibration over silhouette.",
      source_url=S["book_critical_pike"], confidence=4),
    t(5, "Lune décroissante en automne: période major après-midi sur talus 10-15 pieds.",
      "Waning moon in fall: major afternoon period on 10-15 ft breaks.",
      moon_phase="waning", time_of_day="afternoon", season="fall",
      source_url=S["infisherman"], confidence=3),
    t(5, "Brochet ressuscité: rester immobile 10 secondes après une suite, souvent un brochet plus gros suit.",
      "Pike resurrection: stand still 10 seconds after a follow, often a bigger pike trails.",
      source_url=S["book_critical_pike"], confidence=3),
    t(5, "Étang à truite envahi par les brochets: pêcher en bordure avec gros minnowbait jerkbait.",
      "Pike-invaded trout pond: fish edges with a big jerkbait minnow.",
      water_type_id=3, source_url=S["fns"], confidence=2),
    t(5, "Sépaq Lac-Témiscamingue: brochet de plus de 30\" capturé régulièrement juillet-août.",
      "Sepaq Lac-Temiscamingue: pike over 30\" regularly caught July-August.",
      region_id=11, water_type_id=1, season="summer",
      source_url=S["sepaq"], confidence=3),

    # ============================================================
    # 6 — Maskinongé / Muskellunge (≥18 tips)
    # ============================================================
    t(6, "Maski est le 'poisson des 10 000 lancers': patience absolue et changements fréquents.",
      "Muskie is the '10,000-cast fish': absolute patience and frequent changes.",
      source_url=S["book_critical_pike"], confidence=5),
    t(6, "Figure-8 OBLIGATOIRE à chaque lancer: 30% des prises se font dans cette manoeuvre.",
      "Figure-8 MANDATORY on every cast: 30% of strikes happen in this maneuver.",
      source_url=S["book_critical_pike"], confidence=5),
    t(6, "Été chaud: maski reste dans 12-22 pieds près des herbiers profonds, bucktail tandem 1 oz.",
      "Hot summer: muskie holds at 12-22 ft near deep weed edges, 1 oz tandem bucktail.",
      season="summer", temp_water_min_c=18, temp_water_max_c=24,
      source_url=S["infisherman"], confidence=4),
    t(6, "Automne (eau 8-15°C): la plus grosse fenêtre de l'année pour les maskis trophées.",
      "Fall (8-15°C): biggest window of the year for trophy muskie.",
      season="fall", temp_water_min_c=8, temp_water_max_c=15,
      source_url=S["book_critical_pike"], confidence=5),
    t(6, "Suceurs comme appât vif en automne: dérive lente 10-30 pieds avec bobber-stop.",
      "Live suckers in fall: slow drift 10-30 ft with bobber-stop.",
      season="fall", source_url=S["infisherman"], confidence=5),
    t(6, "Pré-frontale: maskinongé chasse activement, jerkbait Suick ou Bull Dawg vitesse rapide.",
      "Pre-front: muskie feeds aggressively, fast-retrieved Suick or Bull Dawg.",
      baro_trend="falling", source_url=S["book_critical_pike"], confidence=5),
    t(6, "Post-frontale froide: souvent journée nulle, mais persister sur les pointes profondes.",
      "Post-cold-front: often a zero day, but persist on deep points.",
      baro_trend="rising", source_url=S["infisherman"], confidence=4),
    t(6, "Pleine lune: période major du soir = pic d'activité maskinongé documenté.",
      "Full moon: evening major period = documented muskie activity peak.",
      moon_phase="full", time_of_day="dusk", source_url=S["infisherman"], confidence=4),
    t(6, "Lune nouvelle: minor matinal souvent productif sur les hauts-fonds 8-12 pieds.",
      "New moon: morning minor often productive on 8-12 ft shallow flats.",
      moon_phase="new", time_of_day="morning", source_url=S["infisherman"], confidence=3),
    t(6, "Bas de ligne titane ou fluoro 130 lb minimum: les maskis brisent tout sinon.",
      "Titanium or 130 lb fluoro leader minimum: muskie breaks everything else.",
      source_url=S["fns"], confidence=5),
    t(6, "Maskinongé de la rivière des Outaouais: structures rocheuses + herbiers près des îles.",
      "Ottawa River muskie: rocky structures + weeds near islands.",
      region_id=11, water_type_id=2, source_url=S["qpeche"], confidence=3),
    t(6, "Lac Saint-François (QC): pêcherie maskinongé de classe mondiale, guides locaux recommandés.",
      "Lac Saint-Francois (QC): world-class muskie fishery, local guides recommended.",
      region_id=11, water_type_id=1, source_url=S["qpeche"], confidence=4),
    t(6, "Topwater en été tôt le matin: prop-bait surface, retrieve constant et bruyant.",
      "Summer topwater early morning: prop-bait surface, constant noisy retrieve.",
      season="summer", time_of_day="dawn", source_url=S["infisherman"], confidence=4),
    t(6, "Bucktail blade ondulant: alterner double-#10 (haute vibration) et single-#13 (gros déplacement d'eau).",
      "Bucktail blade: alternate double-#10 (high vibration) and single-#13 (big water push).",
      source_url=S["book_critical_pike"], confidence=4),
    t(6, "Maski qui suit sans frapper: en figure-8 changer la direction et la profondeur rapidement.",
      "Following muskie that won't strike: in figure-8, change direction and depth rapidly.",
      source_url=S["book_critical_pike"], confidence=5),
    t(6, "Couleur firetiger sur eau teintée; perchaude sur eau claire; blanc/argent par temps couvert.",
      "Firetiger in stained water; perch in clear; white/silver in overcast.",
      source_url=S["infisherman"], confidence=4),
    t(6, "Maskinongé en hiver pas légal au QC: saison du 3e samedi de juin au 31 octobre.",
      "Muskie winter not legal in QC: season 3rd Sat. June to Oct 31.",
      region_id=11, source_url=S["qpeche"], confidence=4),
    t(6, "Trolling profond avec planer board: 12-18 pieds avec gros crankbait Believer ou Jake.",
      "Deep trolling with planer boards: 12-18 ft with big Believer or Jake crankbait.",
      water_type_id=1, source_url=S["infisherman"], confidence=4),
    t(6, "Eau qui se réchauffe brusquement (>3°C en 24h): journée souvent décevante, maski en transition.",
      "Sudden warming (>3°C in 24h): often a poor day, muskie in transition.",
      source_url=S["book_critical_pike"], confidence=3),
    t(6, "Sépaq Réserve Mastigouche: pêche guidée maski mi-juillet à mi-septembre.",
      "Sepaq Mastigouche Reserve: guided muskie mid-July to mid-September.",
      region_id=11, season="summer", source_url=S["sepaq"], confidence=3),

    # ============================================================
    # 7 — Truite mouchetée / Brook Trout (≥18 tips)
    # ============================================================
    t(7, "Truite mouchetée préfère 7-16°C; au-dessus de 20°C la mortalité augmente significativement.",
      "Brook trout prefer 7-16°C; above 20°C mortality rises sharply.",
      source_url=S["dfo"], confidence=5),
    t(7, "Printemps: mouchetées montent dans les tributaires froids pour se nourrir d'invertébrés.",
      "Spring: brook trout move into cold tributaries to feed on invertebrates.",
      season="spring", water_type_id=2, temp_water_min_c=4, temp_water_max_c=12,
      source_url=S["book_critical_trout"], confidence=5),
    t(7, "Petite cuillère tournante #0-1 doré ou argent: classique pour mouchetée en ruisseau.",
      "Small #0-1 gold or silver in-line spinner: classic stream brook trout lure.",
      water_type_id=2, source_url=S["infisherman"], confidence=4),
    t(7, "Ver de terre sur petite hameçon #8 avec plomb fendu: simple et toujours efficace.",
      "Worm on #8 hook with split-shot: simple and always effective.",
      source_url=S["sepaq"], confidence=4),
    t(7, "Été: chercher les fosses ombragées avec arrivée d'eau froide (sources, embouchures).",
      "Summer: seek shaded pools with cold water inflow (springs, mouths).",
      season="summer", water_type_id=2, source_url=S["book_critical_trout"], confidence=5),
    t(7, "Mouche sèche Adams ou Royal Wulff #14: imite plusieurs éphémères locales.",
      "Adams or Royal Wulff dry fly #14: imitates several local mayflies.",
      source_url=S["infisherman"], confidence=4),
    t(7, "Streamer Mickey Finn ou Muddler Minnow: efficace en lac et grand ruisseau.",
      "Mickey Finn or Muddler Minnow streamer: effective in lakes and big streams.",
      source_url=S["book_critical_trout"], confidence=4),
    t(7, "Aube et crépuscule: pics d'éclosion, monter aux mouches sèches en surface.",
      "Dawn and dusk: hatch peaks, fish surface dry flies.",
      time_of_day="dawn", source_url=S["fns"], confidence=4),
    t(7, "Front qui passe: éclosions souvent déclenchées par la chute de pression, fenêtre dorée.",
      "Passing front: hatches often triggered by falling pressure, golden window.",
      baro_trend="falling", source_url=S["book_critical_trout"], confidence=4),
    t(7, "Automne (mi-août à octobre): mouchetées montent dans les tributaires pour frayer.",
      "Fall (mid-Aug to Oct): brook trout run into tributaries to spawn.",
      season="fall", water_type_id=2, source_url=S["book_critical_trout"], confidence=5),
    t(7, "Sépaq Réserve Mastigouche/Portneuf: pêche guidée mouchetée mai-juin.",
      "Sepaq Mastigouche/Portneuf Reserve: guided brook trout May-June.",
      region_id=11, water_type_id=1, season="spring",
      source_url=S["sepaq"], confidence=4),
    t(7, "Pêche d'hiver sur glace: dandinette mini 1/16 oz avec vairon mort sur 3-8 pieds.",
      "Ice fishing: mini 1/16 oz jigging spoon with dead minnow at 3-8 ft.",
      season="winter", region_id=11, source_url=S["qpeche"], confidence=4),
    t(7, "Mouchetée trophée (>4 lb): souvent dans grand lac nordique, troller à 3-6 pieds.",
      "Trophy brook trout (>4 lb): often in northern lakes, troll at 3-6 ft.",
      source_url=S["book_critical_trout"], confidence=3),
    t(7, "Tippet fluorocarbone fin (4-6 lb): essentiel en eau claire et basse pression de pêche.",
      "Light fluorocarbon tippet (4-6 lb): essential in clear water and low fishing pressure.",
      source_url=S["fns"], confidence=4),
    t(7, "Pleine lune sur étang à truite: minor du soir souvent productif, mouche noyée Coachman.",
      "Full moon on a trout pond: evening minor often productive, Coachman wet fly.",
      moon_phase="full", water_type_id=3, time_of_day="dusk",
      source_url=S["infisherman"], confidence=3),
    t(7, "Lune nouvelle: période major matinale en ruisseau, présentations très discrètes.",
      "New moon: morning major in stream, very discreet presentations.",
      moon_phase="new", water_type_id=2, time_of_day="morning",
      source_url=S["infisherman"], confidence=3),
    t(7, "Truite refuse mouche sèche: switcher à nymphe Pheasant Tail #16 en sub-surface.",
      "Trout refuses dry fly: switch to a #16 Pheasant Tail nymph in subsurface.",
      source_url=S["fns"], confidence=4),
    t(7, "Eau qui se réchauffe à 18°C+: privilégier la pêche tôt le matin et libérer rapidement.",
      "Water warming to 18°C+: prioritize early morning and release fish quickly.",
      temp_water_min_c=18, source_url=S["dfo"], confidence=5),
    t(7, "Réservoir Cabonga (QC): truite mouchetée présente, pêche en train avec spoon argent.",
      "Cabonga Reservoir (QC): brook trout present, troll with silver spoon.",
      region_id=11, water_type_id=1, source_url=S["qpeche"], confidence=3),
    t(7, "Étang de pêche à la mouche: présentation dry-dropper (sèche en surface + nymphe 30 cm sous).",
      "Fly-fishing pond: dry-dropper setup (dry on surface + nymph 30 cm below).",
      water_type_id=3, source_url=S["fns"], confidence=4),

    # ============================================================
    # 8 — Truite arc-en-ciel / Rainbow Trout (≥18 tips)
    # ============================================================
    t(8, "Arc-en-ciel préfère 10-18°C, plus tolérante à la chaleur que la mouchetée mais sensible >22°C.",
      "Rainbow trout prefer 10-18°C, more heat-tolerant than brook trout but stressed above 22°C.",
      source_url=S["dfo"], confidence=5),
    t(8, "Printemps en rivière à truite: nymphe Hare's Ear ou Copper John sous indicateur.",
      "Spring trout river: Hare's Ear or Copper John nymph under indicator.",
      season="spring", water_type_id=2, source_url=S["book_critical_trout"], confidence=4),
    t(8, "Streamer Wooly Bugger noir ou olive: imite sangsue et alevin, efficace toute saison.",
      "Black or olive Wooly Bugger streamer: imitates leech and fry, effective all season.",
      source_url=S["book_critical_trout"], confidence=5),
    t(8, "Été chaud: pêcher la première heure du matin, ralentir entre 11h et 16h, reprendre au crépuscule.",
      "Hot summer: fish first hour AM, slow down 11AM-4PM, ramp up at dusk.",
      season="summer", time_of_day="dawn",
      source_url=S["book_critical_trout"], confidence=4),
    t(8, "Front qui approche: éclosions déclenchées, surveiller émergeants en surface.",
      "Approaching front: hatches triggered, watch for emergers on the surface.",
      baro_trend="falling", source_url=S["fns"], confidence=4),
    t(8, "Post-front (baro hausse): truites profondes et léthargiques, nymphe lourde sur le fond.",
      "Post-front (rising baro): deep lethargic trout, heavy nymph on bottom.",
      baro_trend="rising", source_url=S["book_critical_trout"], confidence=4),
    t(8, "Aube éclosion de midge: tiny #20-22 émergeant en surface tranquille.",
      "Dawn midge hatch: tiny #20-22 emerger in calm surface.",
      time_of_day="dawn", source_url=S["fns"], confidence=4),
    t(8, "Crépuscule éclosion d'éphémère: monter en taille #12-14 caddis ou mayfly.",
      "Dusk mayfly hatch: size up to #12-14 caddis or mayfly.",
      time_of_day="dusk", source_url=S["fns"], confidence=4),
    t(8, "Automne: arc-en-ciel se nourrit fortement, streamers grand format Sex Dungeon ou Sculpzilla.",
      "Fall: rainbow feeds heavily, big Sex Dungeon or Sculpzilla streamers.",
      season="fall", source_url=S["book_critical_trout"], confidence=4),
    t(8, "Pêche en train en lac: spoon argent-rouge 1/4 oz à 8-15 pieds avec downrigger.",
      "Lake trolling: silver-red 1/4 oz spoon at 8-15 ft with downrigger.",
      water_type_id=1, source_url=S["infisherman"], confidence=4),
    t(8, "Truite arc-en-ciel ensemencée: souvent près de la rampe de mise à l'eau les 2 premiers jours.",
      "Stocked rainbow: often near the boat ramp the first 2 days after stocking.",
      source_url=S["fns"], confidence=3),
    t(8, "Tippet 5X-6X (4-3 lb) en eau claire: dégradation rapide, vérifier nœuds chaque trois prises.",
      "5X-6X tippet (4-3 lb) in clear water: degrades fast, check knots every 3 fish.",
      source_url=S["fns"], confidence=4),
    t(8, "Pleine lune d'automne: période major en soirée sur les rivières steelhead.",
      "Fall full moon: evening major period on steelhead rivers.",
      moon_phase="full", time_of_day="dusk", season="fall",
      source_url=S["infisherman"], confidence=3),
    t(8, "Lune nouvelle: minor matinal souvent productif sur les fosses froides.",
      "New moon: morning minor often productive on cold pools.",
      moon_phase="new", time_of_day="morning", source_url=S["infisherman"], confidence=3),
    t(8, "Présentation drift sans drag: clé absolue pour mouche sèche en courant.",
      "Drag-free drift: absolute key for dry fly in current.",
      water_type_id=2, source_url=S["fns"], confidence=5),
    t(8, "Indicateur règlable: 1.5x à 2x la profondeur estimée du courant.",
      "Adjustable strike indicator: 1.5x to 2x the estimated current depth.",
      source_url=S["fns"], confidence=4),
    t(8, "Power-bait pour ensemencées: boule rose-orange 30-50 cm au-dessus de l'hameçon.",
      "Power-bait for stockers: pink-orange ball 30-50 cm above the hook.",
      source_url=S["fns"], confidence=3),
    t(8, "Eau muddy après pluie: streamer noir grand format, vibration > visuel.",
      "Muddy water after rain: big black streamer, vibration over visual.",
      source_url=S["book_critical_trout"], confidence=4),
    t(8, "Sépaq Lac Sacacomie / Mauricie: arc-en-ciel ensemencée régulièrement, pêche guidée.",
      "Sepaq Lac Sacacomie / Mauricie: regularly stocked rainbow, guided fishing.",
      region_id=11, water_type_id=1, source_url=S["sepaq"], confidence=3),
    t(8, "Lac Memphrémagog (QC): arc-en-ciel migratrice présente, troller 10-20 pieds avec planer.",
      "Lake Memphremagog (QC): migratory rainbow present, troll 10-20 ft with planer board.",
      region_id=11, water_type_id=1, source_url=S["qpeche"], confidence=3),

    # ============================================================
    # 9 — Truite brune / Brown Trout (≥18 tips)
    # ============================================================
    t(9, "Truite brune est la plus méfiante des salmonidés: présentations fines et tippet fluoro.",
      "Brown trout is the wariest salmonid: finesse presentations and fluoro tippet.",
      source_url=S["book_critical_trout"], confidence=5),
    t(9, "Tolère 12-19°C, plus chaud que mouchetée mais surveiller >22°C.",
      "Tolerates 12-19°C, warmer than brook trout but watch above 22°C.",
      source_url=S["dfo"], confidence=4),
    t(9, "Brune adulte est piscivore: gros streamer 4-6\" articulé en strip rapide.",
      "Adult brown is piscivorous: big 4-6\" articulated streamer stripped fast.",
      source_url=S["book_critical_trout"], confidence=5),
    t(9, "Aube et crépuscule: meilleurs moments pour la brune, en particulier les gros spécimens.",
      "Dawn and dusk: best times for brown, especially trophy fish.",
      time_of_day="dawn", source_url=S["fns"], confidence=5),
    t(9, "Mouse pattern en surface la nuit: technique gagnante pour brunes trophées.",
      "Mouse pattern on surface at night: winning technique for trophy browns.",
      time_of_day="night", source_url=S["book_critical_trout"], confidence=4),
    t(9, "Mouche sèche Stimulator orange #10: imite stoneflies et caddis adultes en été.",
      "Orange Stimulator dry fly #10: imitates summer stoneflies and adult caddis.",
      season="summer", source_url=S["fns"], confidence=4),
    t(9, "Front qui approche: brune monte chasser dans les hauts-fonds.",
      "Approaching front: brown moves up to feed in shallows.",
      baro_trend="falling", source_url=S["book_critical_trout"], confidence=4),
    t(9, "Post-front froid: brune se cache sous billots et sous-berges, présentation très lente.",
      "Post-cold-front: brown hides under logs and undercut banks, very slow presentation.",
      baro_trend="rising", source_url=S["book_critical_trout"], confidence=4),
    t(9, "Automne (frai): brunes mâles agressives sur les frayères, ne pas insister en respect.",
      "Fall (spawn): aggressive male browns on redds, do not pressure out of respect.",
      season="fall", source_url=S["dfo"], confidence=5),
    t(9, "Pêche en lac: troller streamer profond 12-25 pieds avec downrigger en été.",
      "Lake fishing: troll deep streamer 12-25 ft with downrigger in summer.",
      season="summer", water_type_id=1, source_url=S["infisherman"], confidence=3),
    t(9, "Wooly Bugger noir #8 ou #10: standard pour brune toute saison.",
      "Black Wooly Bugger #8 or #10: standard for brown all season.",
      source_url=S["fns"], confidence=4),
    t(9, "Streamer Sex Dungeon en automne: gros profil pour brunes pré-frai.",
      "Sex Dungeon streamer in fall: big profile for pre-spawn browns.",
      season="fall", source_url=S["book_critical_trout"], confidence=4),
    t(9, "Pleine lune nuit chaude d'été: mouse pattern sur surface tranquille.",
      "Hot summer full-moon night: mouse pattern on calm surface.",
      moon_phase="full", time_of_day="night", season="summer",
      source_url=S["book_critical_trout"], confidence=3),
    t(9, "Lune décroissante: minor matinal sur fosses profondes, nymphe stonefly lourde.",
      "Waning moon: morning minor on deep pools, heavy stonefly nymph.",
      moon_phase="waning", time_of_day="morning", source_url=S["infisherman"], confidence=3),
    t(9, "Indicateur de pêche: brunes refusent souvent un indicateur visible, préférer un knot indicator.",
      "Strike indicator: browns often refuse a visible indicator, prefer a knot indicator.",
      source_url=S["fns"], confidence=4),
    t(9, "Tippet 4X fluorocarbone (6 lb) pour streamer; 5X (5 lb) pour nymphe; 6X (4 lb) pour sèche.",
      "4X fluorocarbon tippet (6 lb) for streamer; 5X (5 lb) for nymph; 6X (4 lb) for dry.",
      source_url=S["fns"], confidence=4),
    t(9, "Brune en rivière à courant rapide: viser les contre-courants et les zones d'ombre.",
      "Fast-current river brown: target seams and shadow zones.",
      water_type_id=2, source_url=S["book_critical_trout"], confidence=4),
    t(9, "Étang à truite ensemencé: brune souvent solitaire près des structures submergées.",
      "Stocked trout pond: brown often solitary near submerged structure.",
      water_type_id=3, source_url=S["fns"], confidence=3),
    t(9, "Rivière Jacques-Cartier (QC): brunes ensemencées et naturelles, pêche à la mouche populaire.",
      "Jacques-Cartier River (QC): stocked and wild browns, popular fly fishing.",
      region_id=11, water_type_id=2, source_url=S["qpeche"], confidence=3),
    t(9, "Brune trophée >5 lb: jerkbait suspendu en lac, pauses 4-6 secondes.",
      "Trophy brown >5 lb: suspending jerkbait in lake, 4-6 sec pauses.",
      water_type_id=1, source_url=S["infisherman"], confidence=3),
]
