"""Curated angling tips data for tips.csv.

Each entry is a dict with keys matching the tips schema (minus auto id).
Sources cited where confidence >= 3 per plan-3 §Data Quality.

Coverage target: >=18 tips per species across 15 species.
Mix of season, baro_trend, moon_phase, time_of_day for breadth.
Region 11 = Quebec (QC).
"""

from __future__ import annotations


# Common source URLs (kept short, referenced by name in the data)
S = {
    "sepaq": "https://www.sepaq.com/peche/index.dot",
    "qpeche": "https://www.quebecpeche.com/",
    "dfo": "https://www.dfo-mpo.gc.ca/species-especes/profiles-profils-eng.html",
    "infisherman": "https://www.in-fisherman.com/editorial/",
    "bassmaster": "https://www.bassmaster.com/tips/",
    "fns": "https://www.fieldandstream.com/fishing/",
    "infopeche": "https://infopeche.com/",
    "book_lindner": "book://lindner/multi-species-angler/ch3",
    "book_critical_walleye": "book://in-fisherman/critical-concepts/walleye",
    "book_critical_bass": "book://in-fisherman/critical-concepts/largemouth-bass",
    "book_critical_pike": "book://in-fisherman/critical-concepts/pike-muskie",
    "book_critical_trout": "book://in-fisherman/critical-concepts/trout",
}


# Helper to build a row dict
def t(
    species_id: int,
    fr: str,
    en: str,
    *,
    region_id: int | str = "",
    water_type_id: int | str = "",
    season: str = "any",
    baro_trend: str = "any",
    moon_phase: str = "any",
    temp_water_min_c: float | str = "",
    temp_water_max_c: float | str = "",
    time_of_day: str = "any",
    source_url: str = "",
    confidence: int = 3,
) -> dict[str, str]:
    return {
        "species_id": str(species_id),
        "region_id": str(region_id),
        "water_type_id": str(water_type_id),
        "season": season,
        "baro_trend": baro_trend,
        "moon_phase": moon_phase,
        "temp_water_min_c": str(temp_water_min_c),
        "temp_water_max_c": str(temp_water_max_c),
        "time_of_day": time_of_day,
        "tip_text_fr": fr,
        "tip_text_en": en,
        "source_url": source_url,
        "confidence": str(confidence),
    }


TIPS: list[dict[str, str]] = [
    # ============================================================
    # 1 — Achigan à grande bouche / Largemouth Bass (≥18 tips)
    # ============================================================
    t(
        1,
        "Au printemps, cibler les baies peu profondes au sud du lac qui réchauffent en premier; les bass migrent vers ces zones pour la reproduction.",
        "In spring, target shallow southern bays that warm first; bass migrate there to spawn.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=12,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Période de fraie: ralentir les présentations sur les nids visibles, ver souple no-weight type Senko en pitching court.",
        "Spawn window: slow presentations on visible beds with a weightless stick-worm pitched short.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=15,
        temp_water_max_c=20,
        source_url=S["book_critical_bass"],
        confidence=5,
    ),
    t(
        1,
        "Après-fraie: les femelles épuisées restent près des herbiers; jig finesse ou tube en glissement lent.",
        "Post-spawn: spent females linger near weed edges; finesse jig or tube glided slowly.",
        season="spring",
        baro_trend="steady",
        water_type_id=1,
        temp_water_min_c=18,
        temp_water_max_c=22,
        time_of_day="morning",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Été chaud (>25°C surface): pêcher en début de matinée et tard en soirée, topwater walking sur platières herbeuses.",
        "Hot summer (>25°C surface): fish early and late, walking topwater over weedy flats.",
        season="summer",
        water_type_id=1,
        temp_water_min_c=22,
        temp_water_max_c=28,
        time_of_day="dawn",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Mi-journée d'été: les bass descendent sur le bord des herbiers profonds; Texas rig avec ver souple en glissement.",
        "Summer midday: bass drop to deep weed edges; Texas-rig worm dragged slowly.",
        season="summer",
        water_type_id=1,
        time_of_day="midday",
        temp_water_max_c=28,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Pression barométrique en chute avant un orage: fenêtre dorée pour le topwater et les spinnerbaits rapides.",
        "Falling pressure before a storm: golden window for topwater and fast-moving spinnerbaits.",
        season="summer",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        1,
        "Après le passage d'un front froid: rétrograder vers le drop-shot ou shaky head, ralentir au maximum.",
        "After a cold-front passage: downshift to drop-shot or shaky head, slow it way down.",
        baro_trend="rising",
        source_url=S["book_critical_bass"],
        confidence=5,
    ),
    t(
        1,
        "Automne: les bass suivent les bancs de gardons; crankbait à bavette moyenne en imitation de proie.",
        "Fall: bass follow shad schools; medium-bill crankbait in baitfish patterns.",
        season="fall",
        water_type_id=1,
        temp_water_min_c=12,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Fin d'automne en eau qui refroidit: jerkbait suspendu avec pauses longues de 4-8 secondes.",
        "Late fall as water cools: suspending jerkbait with long 4-8 sec pauses.",
        season="fall",
        temp_water_min_c=8,
        temp_water_max_c=14,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        1,
        "Eau muddy après pluie: leurres avec vibration et profil contrasté (chartreuse/noir), spinnerbait pale Colorado.",
        "Muddy water after rain: vibrating lures with high-contrast profile (chartreuse/black), Colorado-blade spinnerbait.",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        1,
        "Pleine lune chaude: activité nocturne accrue sur les pointes, jig noir trainé lentement.",
        "Warm full moon: increased night activity on points; black jig dragged slowly.",
        moon_phase="full",
        time_of_day="night",
        season="summer",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        1,
        "Eau teintée (visibilité 30-60 cm): leurres en chartreuse ou orange, vibration > silhouette.",
        "Stained water (30-60 cm visibility): chartreuse or orange lures, vibration over silhouette.",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Bordures de nénuphars: pitching d'un creature-bait en Texas rig avec poids 3/8 oz pour pénétrer.",
        "Lily pad edges: pitch a creature-bait Texas-rigged with a 3/8 oz weight to punch through.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Quais et débarcadères: pitching skip avec ver souple sous l'ombre, 2-4 pieds de profondeur.",
        "Docks: skip a soft stick worm into the shadow line, 2-4 ft deep.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Au Québec, les bass de plus de 4 lb se prennent souvent sur des points rocheux avec herbiers adjacents.",
        "In Quebec, bass over 4 lb often come off rocky points with adjacent weeds.",
        region_id=11,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        1,
        "Eau froide de printemps (<12°C): suspending jerkbait à 5-10 pieds, pauses très longues.",
        "Early-spring cold water (<12°C): suspending jerkbait at 5-10 ft, very long pauses.",
        season="spring",
        temp_water_min_c=8,
        temp_water_max_c=12,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        1,
        "Tournoi: alterner deux patterns différents (power-fishing matin, finesse midi) pour maximiser le poids.",
        "Tournament: alternate two patterns (power-fishing AM, finesse midday) to maximize weight.",
        source_url=S["bassmaster"],
        confidence=3,
    ),
    t(
        1,
        "Bouillonnements de surface: lancer immédiatement un walking topwater ou un buzzbait derrière la commotion.",
        "Surface boils: cast a walking topwater or buzzbait right behind the commotion immediately.",
        season="summer",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        1,
        "Lune décroissante en eau claire: présentations finesse drop-shot ou Neko en couleurs naturelles.",
        "Waning moon in clear water: finesse drop-shot or Neko-rig in natural colors.",
        moon_phase="waning",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        1,
        "Petits étangs urbains: lancer parallèle à la berge avec un swim jig en glissement constant.",
        "Small urban ponds: cast parallel to the bank with a steady swim-jig retrieve.",
        water_type_id=3,
        source_url=S["fns"],
        confidence=3,
    ),
    # ============================================================
    # 2 — Achigan à petite bouche / Smallmouth Bass (≥18 tips)
    # ============================================================
    t(
        2,
        "Smallmouth aime les fonds rocheux et le courant; les pointes rocheuses sont des aimants à smallies.",
        "Smallmouth love rocky bottoms and current; rocky points are smallie magnets.",
        water_type_id=1,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Printemps en eau qui se réchauffe (10-15°C): tube sur fond, dragué lentement sur sable et roches.",
        "Spring as water warms (10-15°C): tube bait dragged slowly along sand and rock.",
        season="spring",
        temp_water_min_c=10,
        temp_water_max_c=15,
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        2,
        "Période de fraie: nids visibles sur fond de sable ou gravier; ne pas insister pour la conservation de l'espèce.",
        "Spawn: visible beds on sand or gravel; do not pressure for conservation reasons.",
        season="spring",
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        2,
        "Été: drop-shot avec petit ver flick-shake à 10-25 pieds sur talus rocheux.",
        "Summer: drop-shot with small flick-shake worm at 10-25 ft on rocky breaks.",
        season="summer",
        temp_water_min_c=18,
        temp_water_max_c=24,
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Smallie chasseur en surface: walking topwater couleur naturelle (gris/blanc) au lever du jour.",
        "Surface-feeding smallie: walking topwater in natural colors (gray/white) at dawn.",
        time_of_day="dawn",
        season="summer",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Rivières à courant modéré: jig finesse 1/8 oz dérivé dans les replats derrière les roches.",
        "Moderate-current rivers: 1/8 oz finesse jig drifted in slack water behind boulders.",
        water_type_id=2,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Front froid: les smallies se collent au fond et refusent les présentations rapides; ned rig en glissement.",
        "Cold front: smallies hug bottom and refuse fast moves; Ned rig dragged slowly.",
        baro_trend="rising",
        source_url=S["bassmaster"],
        confidence=5,
    ),
    t(
        2,
        "Pré-frontale: jerkbait suspendu en couleur ayu ou perchaude, twitch-twitch-pause de 3 sec.",
        "Pre-front: suspending jerkbait in ayu or perch color, twitch-twitch-3sec-pause.",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Automne: smallies se concentrent sur les pointes vers le lac principal; crankbait deep en imitation de proie.",
        "Fall: smallies gang up on main-lake points; deep crankbait in baitfish patterns.",
        season="fall",
        temp_water_min_c=10,
        temp_water_max_c=18,
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Eau claire (>3 m de visibilité): fluorocarbone fin (6-8 lb) et présentations naturelles.",
        "Clear water (>3 m visibility): light fluorocarbon (6-8 lb) and natural presentations.",
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        2,
        "Au Québec, le fleuve Saint-Laurent abrite des smallies trophées (>4 lb) près des îles rocheuses.",
        "In Quebec, the St. Lawrence holds trophy smallies (>4 lb) near rocky islands.",
        region_id=11,
        water_type_id=4,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        2,
        "Sépaq: dans les réserves fauniques, viser tôt le matin et fin d'après-midi en juin-juillet.",
        "Sepaq: in wildlife reserves, target early morning and late afternoon in June-July.",
        region_id=11,
        season="summer",
        source_url=S["sepaq"],
        confidence=4,
    ),
    t(
        2,
        "Smallmouth en hiver (eau <8°C): jig hair en couleurs naturelles, présentation extrêmement lente sur fond.",
        "Winter smallmouth (<8°C): hair jig in natural colors, extremely slow bottom presentation.",
        season="winter",
        temp_water_max_c=8,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        2,
        "Pleine lune d'été: activité crépusculaire prolongée jusqu'à 22h sur les pointes.",
        "Summer full moon: extended dusk activity until 10 PM on points.",
        moon_phase="full",
        time_of_day="dusk",
        season="summer",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        2,
        "Goujon (gobie) abondant: imiter avec un tube brun-vert ou ned rig couleur cigare.",
        "Where round gobies are abundant: imitate with a brown-green tube or cigar-colored Ned rig.",
        source_url=S["bassmaster"],
        confidence=4,
    ),
    t(
        2,
        "Rivière des Outaouais et fleuve: drop-shot lourd 1/2 oz pour tenir dans le courant 20-30 pieds.",
        "Ottawa River / St. Lawrence: heavy 1/2 oz drop-shot to hold in 20-30 ft current.",
        water_type_id=4,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        2,
        "Smallie agressif: spinnerbait double-willow chartreuse-blanc retiré rapidement près des roches.",
        "Aggressive smallie: chartreuse-white double-willow spinnerbait reeled fast near rocks.",
        source_url=S["bassmaster"],
        confidence=3,
    ),
    t(
        2,
        "Eau muddy après tempête: les smallies se déplacent vers les pointes peu profondes; vibration > visuel.",
        "Muddy water after storm: smallies move to shallow points; vibration over visual.",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        2,
        "Lune nouvelle: période minor matinale très productive sur les talus de 15-20 pieds.",
        "New moon: morning minor period very productive on 15-20 ft breaks.",
        moon_phase="new",
        time_of_day="morning",
        source_url=S["infisherman"],
        confidence=3,
    ),
    # ============================================================
    # 3 — Doré jaune / Walleye (≥18 tips)
    # ============================================================
    t(
        3,
        "Doré préfère la basse lumière: aube, crépuscule et nuit nuageuse, surtout dans l'eau claire.",
        "Walleye prefer low light: dawn, dusk and overcast nights, especially in clear water.",
        time_of_day="dawn",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Printemps post-fraie: jig 1/4 oz avec ver de terre dérivé sur fonds graveleux 6-12 pieds.",
        "Post-spawn spring: 1/4 oz jig with worm drifted on 6-12 ft gravel.",
        season="spring",
        water_type_id=1,
        temp_water_min_c=10,
        temp_water_max_c=15,
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Été sur grand lac: troller un crawler harness 1.0-1.5 mph sur les structures profondes 20-35 pieds.",
        "Summer on big water: troll crawler harness 1.0-1.5 mph on deep 20-35 ft structures.",
        season="summer",
        water_type_id=1,
        temp_water_min_c=18,
        temp_water_max_c=24,
        source_url=S["infisherman"],
        confidence=5,
    ),
    t(
        3,
        "Doré préfère les températures 13-21°C; au-dessus de 24°C, il descend en profondeur sous la thermocline.",
        "Walleye prefer 13-21°C; above 24°C they drop below the thermocline.",
        source_url=S["dfo"],
        confidence=5,
    ),
    t(
        3,
        "Crépuscule: remontée des dorés sur les pointes; jig 3/8 oz avec ver ou vairon.",
        "Dusk: walleye move up onto points; 3/8 oz jig with worm or minnow.",
        time_of_day="dusk",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Doré en eau teintée (Saint-Laurent, rivières du Bouclier): meilleur que le doré en eau claire pour les heures de midi.",
        "Stained water walleye (St. Lawrence, Shield rivers): more active midday than clear-water walleye.",
        time_of_day="midday",
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Tendance baro chute: les dorés montent et chassent activement; crankbait shallow en couleur tigre.",
        "Falling barometer: walleye come up and feed actively; shallow tiger-pattern crankbait.",
        baro_trend="falling",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Post-front (baro hausse): retour aux jigs lents sur fond, vairon mort sur jig 1/8 oz.",
        "Post-front (rising baro): back to slow jigs on bottom, dead minnow on 1/8 oz jig.",
        baro_trend="rising",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Pleine lune d'été: pêche nocturne très efficace sur les hauts-fonds 6-10 pieds.",
        "Summer full moon: night fishing very effective on 6-10 ft shallow flats.",
        moon_phase="full",
        time_of_day="night",
        season="summer",
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Lac Saint-Jean (QC): doré et ouananiche cohabitent; troller à 8-12 pieds avec spoon argent-bleu.",
        "Lac Saint-Jean (QC): walleye and landlocked salmon coexist; troll 8-12 ft with silver-blue spoon.",
        region_id=11,
        water_type_id=1,
        source_url=S["qpeche"],
        confidence=3,
    ),
    t(
        3,
        "Automne: les dorés se gavent avant l'hiver; jerkbait suspendu en eau de 10-20 pieds, pauses 5-8 sec.",
        "Fall: walleye feed up before winter; suspending jerkbait in 10-20 ft, 5-8 sec pauses.",
        season="fall",
        temp_water_min_c=8,
        temp_water_max_c=14,
        source_url=S["infisherman"],
        confidence=4,
    ),
    t(
        3,
        "Hiver (pêche blanche): vairon vif sur dandinette dorée 1/4 oz, à 1-2 pieds du fond.",
        "Winter (ice fishing): live minnow on gold jigging spoon 1/4 oz, 1-2 ft off bottom.",
        season="winter",
        temp_water_max_c=4,
        region_id=11,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Vent qui souffle vers une berge: les dorés se concentrent côté vagues, où le plancton s'accumule.",
        "Wind blowing into a shoreline: walleye stack on the wave-washed side where plankton concentrates.",
        source_url=S["book_critical_walleye"],
        confidence=5,
    ),
    t(
        3,
        "Période minor solunar coïncidant avec crépuscule: probabilité élevée d'un pic d'activité.",
        "Solunar minor period overlapping dusk: high probability of an activity spike.",
        time_of_day="dusk",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        3,
        "Doré refuse une présentation: changer la couleur (jaune-vif, orange) avant la taille du leurre.",
        "Walleye refuses a presentation: switch color (bright yellow, orange) before switching lure size.",
        source_url=S["book_critical_walleye"],
        confidence=4,
    ),
    t(
        3,
        "Embouchure de rivière au printemps: dorés en remontée, jig 1/4 oz avec twister sur talus.",
        "River mouth in spring: ascending walleye, 1/4 oz jig with twister tail on breakline.",
        season="spring",
        water_type_id=2,
        source_url=S["qpeche"],
        confidence=4,
    ),
    t(
        3,
        "Lune nouvelle: période major nocturne, troller lentement (1.0 mph) avec crankbait shad.",
        "New moon: major night period, troll slowly (1.0 mph) with shad crankbait.",
        moon_phase="new",
        time_of_day="night",
        source_url=S["infisherman"],
        confidence=3,
    ),
    t(
        3,
        "Doré de trophée (>8 lb): souvent solitaire, sur structure isolée; live bait rig avec vairon de 15 cm.",
        'Trophy walleye (>8 lb): often solitary on isolated structure; live-bait rig with 6" sucker.',
        source_url=S["book_critical_walleye"],
        confidence=4,
    ),
    t(
        3,
        "Doré jaune sépaq Lac-Bouchard: pêche guidée mai-juin, jig vert-orange préféré.",
        "Sepaq Lac-Bouchard walleye: guided May-June fishing, green-orange jig preferred.",
        region_id=11,
        water_type_id=1,
        season="spring",
        source_url=S["sepaq"],
        confidence=3,
    ),
]
